
-- ----------------------------
-- One-Click Report Search Criteria Records,Assume that search_criteria's primary key of each(DB) is less than 100000;
-- ----------------------------

INSERT INTO `search_criteria` VALUES ('100000', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100001', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100002', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100003', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100004', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100005', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100006', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100007', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100008', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100009', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100010', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100011', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100012', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100013', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100014', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100015', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100016', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100017', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100018', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100019', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100020', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100021', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100022', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100023', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100024', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100025', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100026', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100027', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100028', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100029', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100030', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100031', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100032', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100033', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100034', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100035', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100036', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100037', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100038', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100039', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100040', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100041', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100042', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100043', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100044', '-30772', null, null, null, null, null);
INSERT INTO `search_criteria` VALUES ('100045', '-30772', null, null, null, null, null);


-- ----------------------------
-- One-Click Report Search Token Records 
-- ----------------------------

INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100001', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100001', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100001', '0', '1', 'Transaction Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100002', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100002', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 LastMonthEnd; 8 LastMonthStart', null, '100002', '0', '1', 'Transaction Date', ' Less & Equal LastMonthEnd; Greater & Equal LastMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100000', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100000', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 6 CurrentCalendarYearStart; 7 CurrentCalendarYearEnd', null, '100000', '0', '1', 'Transaction Date', ' Greater Than CurrentCalendarYearStart; Less & Equal CurrentCalendarYearEnd', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100005', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100005', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'membership_listing.enrollmentDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100005', '0', '1', 'Enrollment Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100006', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100006', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'membership_listing.enrollmentDate', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100006', '0', '1', 'Enrollment Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100010', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100010', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'shopping_cart_items.sellingItemType', '5', '1', '100010', '0', '1', 'Item Type', 'PRODUCT', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100010', '1', '1', 'Transaction Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100018', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100018', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100027', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100027', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100028', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100028', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'payment.tenderId', '2', '1', '100028', '0', '1', 'Transaction Tender', 'Credit Card (Offline)', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100028', '1', '1', 'Transaction Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'payment.tenderId', '4', '1', '100028', '0', '2', 'Transaction Tender', 'Credit Card (Online)', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100028', '1', '2', 'Transaction Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100029', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100029', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'payment.tenderId', '2', '1', '100029', '0', '1', 'Transaction Tender', 'Credit Card (Offline)', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 LastMonthEnd; 8 LastMonthStart', null, '100029', '1', '1', 'Transaction Date', ' Less & Equal LastMonthEnd; Greater & Equal LastMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'payment.tenderId', '4', '1', '100029', '0', '2', 'Transaction Tender', 'Credit Card (Online)', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 LastMonthEnd; 8 LastMonthStart', null, '100029', '1', '2', 'Transaction Date', ' Less & Equal LastMonthEnd; Greater & Equal LastMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100030', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100030', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100032', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100032', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100031', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100031', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100037', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100037', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100038', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100038', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100022', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100022', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100009', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100009', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'shopping_cart_items.sellingItemType', '5', '1', '100009', '0', '1', 'Item Type', 'PRODUCT', '7');
INSERT INTO `search_token` VALUES (null, 'shopping_cart.createTime', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100009', '1', '1', 'Transaction Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100045', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100045', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100039', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100039', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100040', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100040', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100041', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100041', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100042', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100042', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100044', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100044', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100043', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100043', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100003', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100003', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100003', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.donationDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100003', '0', '1', 'Donation Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100004', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100004', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100004', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.donationDate', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100004', '0', '1', 'Donation Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100014', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100014', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100014', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.tenderId', '( \'\'4\'\', \'\'12\'\')', '9', '100014', '0', '1', 'Tender', '( \'\'Credit Card (Online)\'\', \'\'E-Check/ACH\'\')', '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100015', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100015', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100015', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.tenderId', '( \'\'4\'\', \'\'12\'\')', '10', '100015', '0', '1', 'Tender', '( \'\'Credit Card (Online)\'\', \'\'E-Check/ACH\'\')', '7');
INSERT INTO `search_token` VALUES (null, 'donation.donationType', '( \'\'1\'\', \'\'3\'\')', '9', '100015', '0', '1', 'Donation Type', '( \'\'DONATION\'\', \'\'PLEDGEPAYMENT\'\')', '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100025', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100025', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100025', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.expectedDate', 'CurrentDay', '6', '100025', '0', '1', 'Expected Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'donation.closedTime', '', '3', '100025', '1', '1', 'Closed Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100023', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100023', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100023', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.donationDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100023', '0', '1', 'Pledge Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100024', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100024', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100024', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.closedTime', '', '3', '100024', '0', '1', 'Closed Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100026', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100026', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100026', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'donation.closedTime', '', '3', '100026', '0', '1', 'Closed Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'donation.expectedDate', 'CurrentDay', '5', '100026', '1', '1', 'Expected Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100017', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100017', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100017', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'recurring_donation.endDate', 'CurrentDay', '6', '100017', '0', '1', 'Recurring End Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'recurring_donation.endDate', '', '3', '100017', '0', '2', 'Recurring End Date', null, '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100013', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100013', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100013', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100013', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100012', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100012', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100012', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100012', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100016', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100016', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100016', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'campaign.startDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100016', '0', '1', 'Start Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100007', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100007', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100007', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'event.startDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100007', '0', '1', 'Start Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100008', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100008', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100008', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'event.startDate', ' 7 CurrentMonthEnd; 8 CurrentMonthStart', null, '100008', '0', '1', 'Start Date', ' Less & Equal CurrentMonthEnd; Greater & Equal CurrentMonthStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100020', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100020', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100020', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'event.startDate', ' 7 CurrentCalendarYearEnd; 8 CurrentCalendarYearStart', null, '100020', '0', '1', 'Start Date', ' Less & Equal CurrentCalendarYearEnd; Greater & Equal CurrentCalendarYearStart', '4');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100011', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100011', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100011', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100011', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100036', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100036', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100036', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100036', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100021', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100021', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100021', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100021', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100033', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100033', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100033', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100033', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100034', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100034', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100034', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100034', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100035', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100035', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100035', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'account.id', '', '4', '100035', '0', '1', 'Account ID', null, '7');
INSERT INTO `search_token` VALUES (null, 'statsType', '1', 'GRPBY', '100019', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'includeOtherEmails', '0', 'GRPBY', '100019', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'forEmail', '0', 'GRPBY', '100019', '0', null, null, null, null);
INSERT INTO `search_token` VALUES (null, 'event.id', '', '4', '100019', '0', '1', 'Event', '', '7');


